backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "events"
    label: "Eventos"
    files:
      - name: "events"
        label: "Lista de eventos"
        file: "events.json"
        format: "json"
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "TÃ­tulo", name: "title", widget: "string" }
              - { label: "Data", name: "date", widget: "string" }